# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: intelligent-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intelligent-app
  template:
    metadata:
      labels:
        app: intelligent-app
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: intelligent-app
          image: <name-of-azure-container-registry>.azurecr.io/intelligent-app:v1
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_DEBUG
              value: "1"
            - name: VISION_KEY
              value: <THE-KEY-1-VALUE-FROM-YOUR-COGNITIVE-SERVICE>
            - name: VISION_ENDPOINT
              value: <THE-ENDPOINT-VALUE-FROM-YOUR-COGNITIVE-SERVICE>
            - name: COSMOS_ACCOUNT_CONNECTION_STRING
              value: <YOUR-COSMOS-ACCOUNT-CONNECTION-STRING>
            - name: COSMOS_ACCOUNT_HOST
              value: <YOUR-COSMOS-ACCOUNT-HOST>
            - name: COSMOS_ACCOUNT_KEY
              value: <YOUR-COSMOS-ACCOUNT-KEY>
            - name: COSMOS_DATABASE_ID
              value: <YOUR-COSMOS-DATABASE-ID>
            - name: COSMOS_IMAGE_ANALYSIS_CONTAINER_ID
              value: ImageAnalysisContainer
            - name: COSMOS_AGGREGATE_RESULTS_CONTAINER_ID
              value: AggregateResultsContainer
